# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fef6903a05855efec304b11dfc7698bf4955eaaa70d4a3247e73b0621898c7a365b02b02fc4a45bb60e1c84c23119cf86248f124ff7652d0289f27fc1d359f8a

test:
  secret_key_base: 8aa4694227816f11eda32e82cf89bfb724a0013b71be56adc75b6084b0a1851484388b437355bef78bf437b95d39d5a8b489fb0fd9dd299ffd9c813f6f7e8805

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
